### PR TITLE
add proposal templates

### PR DESCRIPTION
**Pull request by abbey-titcomb**
adds proposal templates

Signed-off-by: abbey titcomb <abbeytitcomb@gmail.com>

### CODE REVIEW

**Comment by abbey-titcomb** [comment]
We have to edit these once we finalize the proposal templates.

**Review by shelbeeee — CHANGES_REQUESTED** [review]
Can we change the order of the proposals to be: Executable, Social, Consensus

**Comment by abbey-titcomb** [comment]
Added [org proposal template](https://github.com/radicle-dev/radicle-governance/pull/4/commits/d09a002083918e65c83d87a9c82fb08e03594c3a) (/executeable-org.md).

**Comment by shelbeeee** [comment]
@joelhans can you please change the order of the templates on the template list page (https://github.com/radicle-dev/radicle-governance/tree/proposal-templates/templates) so we can have this ready to merge April 1? The order should be:
- executable
- executable org
- social
- consensus

**Comment by joelhans** [comment]
@shelbeeee Do you mean the directly in the folder you've linked to? I think the only way to do that would be to change the filenames to something like `01_executable.md`, `02_executeabl-org.md`, etc.

I don't believe we reference templates at all on `docs.radicle.community`, but maybe we need to change that!

**Comment by shelbeeee** [comment]
It would be nice to have the templates in the same order as on the manual.
If this means labeling/numbering them like this then I think that is ok.

We mention templates in the Gov Manual but not anywhere explicitly on the
docs. Abbey and realized yesterday that we are going to have to do a full
review of the docs given all of the changes from the past few weeks. We
will keep you updated on anything we decide on.

**Review by shelbeeee — APPROVED** [review]
Looks good now!

**Comment by joelhans** [comment]
> It would be nice to have the templates in the same order as on the manual. If this means labeling/numbering them like this then I think that is ok. We mention templates in the Gov Manual but not anywhere explicitly on the docs. Abbey and realized yesterday that we are going to have to do a full review of the docs given all of the changes from the past few weeks. We will keep you updated on anything we decide on.

Hey, @shelbeeee, that sounds great! Happy to stay in the loop and help you determine the right architecture for all these changes once they're all voted on and/or implemented!

**Pull request merged**
